package queuemonitor;

import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;

/**
 *
 * @author bshteinfeld
 */
public class QMFrame extends javax.swing.JFrame {

    /**
     * Creates new form QMFrame
     */
    public QMFrame() {
        initComponents();
        this.setTitle("IT Helpdesk - Queue Monitor");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        arrivalsTA = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        deptsTA = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        delaysTA = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        statsTA = new javax.swing.JTextArea();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel1.setText("Arrivals:");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel3.setText("Departures:");

        arrivalsTA.setColumns(20);
        arrivalsTA.setRows(5);
        jScrollPane1.setViewportView(arrivalsTA);

        deptsTA.setColumns(20);
        deptsTA.setRows(5);
        jScrollPane2.setViewportView(deptsTA);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel2.setText("Delays:");

        delaysTA.setColumns(20);
        delaysTA.setRows(5);
        jScrollPane3.setViewportView(delaysTA);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel4.setText("Statistics:");

        statsTA.setColumns(20);
        statsTA.setRows(5);
        jScrollPane4.setViewportView(statsTA);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane4)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(632, 632, 632)
                        .addComponent(jLabel2)
                        .addGap(0, 743, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QMFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QMFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QMFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QMFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QMFrame().setVisible(true);
            }
        });
    }

    
    private String ticksToString(ArrayList<Ticket> ticks) {
        if (ticks.isEmpty())
            return "";
        String tickStr = "";
        for(Ticket t: ticks) {
            tickStr += t + "\n";
        }
        return tickStr.substring(0, tickStr.length()-1);
    }
    
    public void updateArrivals(ArrayList<Ticket> ticks) {
        arrivalsTA.setText(ticksToString(ticks));
        if (ticks.isEmpty())
            arrivalsTA.setBackground(new Color(70, 165, 70));
        else
            arrivalsTA.setBackground(new Color(246, 98, 98));
        arrivalsTA.setFont(new Font("Arial", Font.PLAIN, 30));
        arrivalsTA.setEditable(false);
    }
    
    public void updateDeptartures(ArrayList<Ticket> ticks) {
        deptsTA.setText(ticksToString(ticks));
        if (ticks.isEmpty())
            deptsTA.setBackground(new Color(70, 165, 70));
        else
            deptsTA.setBackground(new Color(246, 98, 98));
        deptsTA.setFont(new Font("Arial", Font.PLAIN, 30));
        deptsTA.setEditable(false);
    }
    
    public void updateDelays(ArrayList<Ticket> ticks) {
        delaysTA.setText(ticksToString(ticks));
        if (ticks.isEmpty())
            delaysTA.setBackground(new Color(70, 165, 70));
        else
            delaysTA.setBackground(new Color(246, 98, 98));
        delaysTA.setFont(new Font("Arial", Font.PLAIN, 30));
        delaysTA.setEditable(false);
    }
    
    public void updateStats(String string) {
        statsTA.setText(string);
        statsTA.setFont(new Font("Arial", Font.PLAIN, 25));
        statsTA.setBackground(new Color(70, 165, 70));
        statsTA.setEditable(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea arrivalsTA;
    private javax.swing.JTextArea delaysTA;
    private javax.swing.JTextArea deptsTA;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea statsTA;
    // End of variables declaration//GEN-END:variables
}
